config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'static_pages#home'

  match 'contact' , to: 'static_pages#contact', via: 'get'
  match 'mail' , to: 'static_pages#mail', via: 'post'

  get 'about' => 'static_pages#about'

  resources :projects, only: [:index]

  get '*path' => redirect('/')

end

app/models/admin.rb
class Admin < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :resources

  validates :title, :presence => true
  validates :category, :presence => true

  scope :filter, -> (category) {
    case category
      when 'all'
        all
      when 'indoor_all'
        where(category: %w(indoor_commercial indoor_private))
      when 'indoor_commercial'
        where(category: 'indoor_commercial')
      when 'indoor_private'
        where(category: 'indoor_private')
      when 'building'
        where(category: 'building')
      when 'green_area'
        where(category: 'green_area')
    end
  }

  def category_enum
    [
      ['wewnątrz komercyjnie', 'indoor_commercial'],
      ['wewnątrz prywatne', 'indoor_private'],
      ['teren zielony', 'green_area'],
      ['budynek', 'building']
    ]
  end

end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :project
  has_attached_file :image, :styles => {:small => '370x280>',
                                        :fullhd => '1980x1080'},
                    :region => 'us-east-1'

  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image,
                                    :content_type => /^image\/(png|gif|jpeg)/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :validatable ,:trackable, :rememberable
  # Czemu wywalenie tych 2 opcji pozwala działać tego kurwa nie wiem :D
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # rescue_from ActionView::MissingTemplate, :with => :template_not_found
  # rescue_from ActionController::UnknownFormat, :with => :template_not_found
  # dodac na samym koncu projektu


  private

  def template_not_found
    redirect_to root_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.includes(:resources).filter(params[:category]).order(position: :asc)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @projects = Project.where(show_on_home: true).order(created_at: :desc).includes(:resources).first(3)
  end

  def about
  end

  def contact
  end

  def mail
    MailerNotifierMailer.mail_to_me(params[:name], params[:email], params[:content]).deliver
    redirect_to contact_path, notice: "Twoja wiadomość została wysłana"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "WIZZART"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="spa-wrap-gototop"><span class="spa-gototop"><i class="fa fa-long-arrow-up"></i></span>
</div>
<div class="bottom-sidebar style-01">
  <div class="container">
    <p></p>
    <div class="row white-text-style mh-populor">
      <div class="col-sm-3 col-sm-offset-2" style="height: 200px !important;">
        <div class="widget widget_nav_menu">
          <h3 class="widget-title style-02">
            Media społecznościowe
          </h3>
          <div class="widget-content">
            <ul class="menu">
              <li>
                <%= link_to 'Facebook', 'https://www.facebook.com/Wizzart-Architektura-1191225920953207/?skip_nax_wizard=true', class: 'fa fa-angle-double-right' %>
              </li>
              <li>
                <%= link_to 'Instagram', 'https://www.instagram.com/wizzart_architektura/', class: 'fa fa-angle-double-right' %>
              </li>
              <li>
                <%= link_to 'LinkedIn', 'https://pl.linkedin.com/in/aleksander-śliwiński-66324486/en', class: 'fa fa-angle-double-right' %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-sm-3 col-sm-offset-2" style="height: 200px !important;">
        <div class="widget widget_nav_menu">
          <h3 class="widget-title style-02">
            Kontakt
          </h3>
          <div class="widget-content">
            <ul class="menu">
              <li>
                <%= link_to "<i class='fa fa-phone'></i>Telefon: 504-285-395".html_safe, 'tel:504285395' %>
              </li>
              <li>
                <%= link_to "<i class='fa fa-envelope'></i>Email: wizzart24@gmail.com".html_safe, 'mailto:wizzart24@gmail.com' %>
              </li>
              <li>
                <%= link_to "<i class='fa fa-map-marker'></i>31-147 Kraków, ul. Długa 63/8".html_safe, 'https://goo.gl/maps/WiDtru1PJiA2', target: '_blank' %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<footer class="spa-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <span class="spa-copyright">
          Copyright © <%= Time.now.year %> Made by <%= mail_to 'vladimirkabar@gmail.com', 'Vladimir Kabar', subject: 'Zapytanie o stronę' %>
        </span>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="spa-header style-01">
  <div class="header-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-2 col-sm-3 col-xs-3">
          <%= link_to image_tag('logo.jpg', size: '60x60'), root_path %>
        </div>
        <div class="col-md-10 col-sm-9 col-xs-9 spa-algr">
          <nav class="spa-menu-top">
            <%= render partial: 'layouts/menu' %>
          </nav>
          <div class="spa-search-and-mega">
            <i class="fa fa-align-justify spa-menu-responsive-header"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="spa-wrap-menu-responsive">
    <div class="spa-wrap">
      <button class="spa-close-menu-responsive"><span>x</span>CLOSE</button>
      <nav class="spa-menu-responsive">
        <%= render partial: 'layouts/menu' %>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_menu.html.erb
<ul>
  <li class="<%= 'active' if action_name == 'home' %>">
    <%= link_to "Strona główna", root_path %>
  </li>
  <li class="<%= 'active' if action_name == 'about' %>">
    <%= link_to "O Nas", about_path %>
  </li>
  <li class="<%= 'active' if action_name == 'index' %>">
    <%= link_to "Projekty", projects_path(category: 'all') %>
    <ul>
      <li>
        <%= link_to "Wnętrza", projects_path(category: 'indoor_all') %>
        <ul>
          <li>
            <%= link_to "komercyjne", projects_path(category: 'indoor_commercial') %>
          </li>
          <li>
            <%= link_to "prywatne", projects_path(category: 'indoor_private') %>
          </li>
          <li>
            <%= link_to "wszystkie", projects_path(category: 'indoor_all') %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to "Budynki", projects_path(category: 'building') %>
      </li>
      <li>
        <%= link_to "Tereny zielone", projects_path(category: 'green_area') %>
      </li>
      <li>
        <%= link_to "Wszystkie", projects_path(category: 'all') %>
      </li>
    </ul>
  </li>
  <li class="<%= 'active' if action_name == 'contact' %>">
    <%= link_to "Kontakt", contact_path %>
  </li>
  <li>
    <% if user_signed_in? %>
      <%= link_to("Wyloguj", destroy_user_session_path, :method => :delete) %>
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag 'application.css', media: 'all' %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  <%= javascript_include_tag 'application.js', media: 'all' %>
  <%= javascript_include_tag 'saprol/imagesloaded.pkgd.min.js', media: 'all' %>
  <%= javascript_include_tag 'lib/jquery.browser.js', media: 'all' %>
  <%= javascript_include_tag 'lib/cycle.js', media: 'all'%>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="main-container">
  <%= render 'layouts/header' %>
  <%= yield  :page_title %>
  <div class="main-content">
    <% if notice %>
        <p class="alert alert-success fade-out"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger fade-out"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</div>

</body>

</html>

app/views/projects/_photoswipe.html.erb
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

  <div class="pswp__bg"></div>
  <div class="pswp__scroll-wrap">

    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>

    <div class="pswp__ui pswp__ui--hidden">
      <div class="pswp__top-bar">
        <div class="pswp__counter"></div>
        <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
        <button class="pswp__button pswp__button--share" title="Share"></button>
        <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
        <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

        <div class="pswp__preloader">
          <div class="pswp__preloader__icn">
            <div class="pswp__preloader__cut">
              <div class="pswp__preloader__donut"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
        <div class="pswp__share-tooltip"></div>
      </div>

      <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
      </button>

      <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
      </button>

      <div class="pswp__caption">
        <div class="pswp__caption__center"></div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_project.html.erb
<div class="widget spa-widget-portfolio project-item <%= project.category.gsub('_', ' ') %>">
  <div class="widget-header style-08">
    <span class="sub-title style-03"><%= t(project.category) %></span>
    <h3 class="widget-title style-05"><%= project.title %></h3>
  </div>
  <div class="widget-content">
    <p>
      <%= project.description %>
    </p>
    <ul class="row" style="margin: 0">
      <% project.resources.each do |resource| %>
        <li class="spa-item col-md-3 resource-item">
          <%= image_tag(resource.image.url(:small), :'data-resource-url' => resource.image.url(:fullhd)) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/projects/index.html.erb
<% provide(:title, 'Projekty') %>

<%= content_for :page_title do %>
  <div id="content">
    <div class="rotate" style="display:none;">
      <%= image_tag('projects.jpg', class: 'rest-image') %>
    </div>
  </div>
<% end %>

<section class="spa-area spa-area-17">
  <div class="container">
    <div class="row" style="margin-bottom: 20px;">
    <div class="row">
      <div class="col-md-12">
        <%= render partial: 'photoswipe' %>
        <%= render partial: 'project', collection: @projects %>
      </div>
    </div>
  </div>
</section>

app/views/projects/projects_implementation.html.erb
<% provide(:title, "Projekty : realizacje") %>

<section class="spa-area spa-area-17">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="widget spa-widget-portfolio">
          <div class="widget-header style-08">
            <span class="sub-title style-03">WizzART </span>
            <h3 class="widget-title style-05">Realizacje projektów </h3>
          </div>
          <div class="widget-content">
            <p>Szanowny Kliencie.

              Zajmuję się opracowywaniem projektów wnętrz, architekturą krajobrazu oraz wizualizacją różnorodnych
              produktów. Mogę również przygotować animacje.
              Dzięki foto realistycznej wizualizacji szybko zobaczysz jak mogą wyglądać Twoje zamierzenia, pragnienia,
              pomysły. Zaoszczędzisz czas i pieniądze.
              Realizując zlecenia mam na uwadze zarówno indywidualne potrzeby i wymagania klienta , jak i najnowsze
              światowe trendy w dziedzinie projektowania .
              Szczegóły oferty uzgadniamy z klientem.

            <ul>Oferta projektowa:
              <li>- projekty wnętrz</li>
              <li>- projekty krajobrazu</li>
            </ul>

            </p>

            <%= render 'projects/projects_data/viewtorender' %>

            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/resources/show.html.erb
<%= image_tag @resource.image.url(:small) %>

app/views/static_pages/_project.html.erb
<a href="/projects?category=all">
  <article class="entry-item">
    <div class="entry-thumb">
      <%= image_tag project.resources.first.image.url(:small) %>
      <div class="spa-wrap-thumb-add-feature">
      </div>
      <span class="spa-sale"><%= project.title %></span>
    </div>
    <div class="entry-content woocommerce">
      <div class="spa-wrap-thumb-add-feature">
      </div>
      <p>
        <%= project.description %>
      </p>
    </div>
  </article>
</a>

app/views/static_pages/about.html.erb
<% provide(:title, 'O nas') %>

<%= content_for :page_title do %>
  <div id="content">
    <div class="rotate" style="display:none;">
      <%= image_tag('about.jpg', class: 'rest-image') %>
    </div>
  </div>
<% end %>

<section class="spa-area spa-area-17">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="widget spa-widget-portfolio">
          <div class="widget-header style-08">
            <span class="sub-title style-03"></span>
            <h3 class="widget-title style-05">Kim jestesmy</h3>
          </div>
          <div class="widget-content">
            <p>
              Wizzart to studio zajmujące się projektowaniem wnętrz oraz krajobrazów zarówno dla kilentów biznesowych jak i indywidualnych.
            </p>

            <p>
              Projekty przedstawiamy klientom w fotorealistycznej wizualizacji, dzięki której można zobaczyć przyszły efekt i dopracować go już na etapie projektu.
            </p>

            <p>
              Oferujemy także realizację projektów przez współpracujące z nami firmy oraz nadzór nad wykonawstwem.
            </p>
          </div>

          <br/>

          <div class="widget-header style-08">
            <span class="sub-title style-03"></span>
            <h3 class="widget-title style-05">Nasze realizacje</h3>
          </div>
          <div class="widget-content">
            <p>
              Nasze doświadzenie zdobyliśmy realizując projekty:

              <ul class="disc">
                <li>hoteli i restauracji</li>
                <li>biur, sklepów</li>
                <li>domów i mieszkań</li>
                <li>ogrodów</li>
                <li>przestrzeni wokół budynków publicznych i mieszkalnych</li>
              </ul>
            </p>
          </div>

          <br/>

          <div class="widget-header style-08">
            <span class="sub-title style-03"></span>
            <h3 class="widget-title style-05">Nasze zasady</h3>
          </div>

          <h6>JAKOŚĆ i ESTETYKA</h6>
          <div class="widget-content">
            <p>
              Proponujemy trwałe materiały dobrej jakości i ponadczasowe rozwiązania. Nasze realizacje maja być modne dziś i jutro.
            </p>
          </div>

          <h6>FUNKCJONALNOŚĆ</h6>
          <div class="widget-content">
            <p>
              Stawiamy na funkcjonlanośc przestrzeni i zaspokojenie potrzeb klientów. Nasi klienci muszą czuć się komfortowo w swojej przestrzeni każdego dnia.
            </p>
          </div>

          <h6>ROZSĄDEK</h6>
          <div class="widget-content">
            <p>
              Pracujemy w ramach budżetu. Nasze projekty są kreatywne, ale zawsze możwlie do zrealizowania w założonym budżecie.
            </p>
          </div>

          <br/>
          <br/>

          <p class="sentence">
            <span class="content">„Kreatywność to bawiąca się inteligencja”</span>
            <span class="author">Albert Einstein</span>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Kontakt') %>

<%= content_for :page_title do %>
  <div id="content">
    <div class="rotate" style="display:none;">
      <%= image_tag('contact.jpg', class: 'rest-image') %>
    </div>
  </div>
<% end %>

<section class="spa-area spa-area-17">
  <div class="container">
    <div class="row" style="margin-bottom: 20px;">
      <div class="row">
        <div class="col-md-6 col-md-push-3">

          <div class="widget spa-widget-contact-form">
            <div class="widget-header style-12">
              <span class="sub-title style-03">Wyślij wiadomość </span>
              <h3 class="widget-title style-09">Formularz kontaktowy</h3>
            </div>
            <div class="widget-content">
              <div class="spa-contact-form">
                <%= form_tag('mail') do %>
                  <p>
                    <%= text_field_tag :name, '', :placeholder => 'Imię i nazwisko', required: true %>
                  </p>
                  <p>
                    <%= email_field_tag :email, '', :placeholder => 'Email', required: true %>
                  </p>
                  <p>
                    <%= text_area_tag :content, '', :placeholder => 'Treść wiadomości', required: true %>
                  </p>

                  <div class="spa-submit">
                    <p>
                      <%= submit_tag 'Wyślij wiadomość' %>
                    </p>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
      </div>
    </div>
</section>

app/views/static_pages/home.html.erb
<% provide(:title, "Strona główna") %>

<div id="content">
  <div class="rotate" style="display:none;">
    <%= image_tag('home1.jpg', class: 'main-image') %>
    <%= image_tag('home2.jpg', class: 'main-image') %>
    <%= image_tag('home3.jpg', class: 'main-image') %>
    <%= image_tag('home4.jpg', class: 'main-image') %>
  </div>
</div>

<section class="spa-area spa-area-01">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="widget spa-widget-list-product-intro">
          <div class="widget-header">
            <span class="sub-title">WizzART</span>
            <h3 class="widget-title">Przykładowe projekty</h3>
          </div>
          <div class="widget-content">
            <div class="spa-wrap-owl">
              <div class="owl-carousel">
                <%= render partial: 'project', collection: @projects %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>